#!/bin/sh



jj="27-09"
## jj=`date '+%d-%m'`
# first for North
echo "###start North####"

DAY=` date +%d`
YEAR=` date +%Y`
MONTH=`date +%m`
Time=`date +%H%M%S`

 cd /home/NCOR6649/scripts/act_alm


/bin/perl sunfire2.pl &
/bin/perl sunfire3.pl &
/bin/perl sunfire4.pl &
# /bin/perl somcsys2.pl &
 

sleep 1000 

/bin/sh ftp_act  

echo "### End #####"



 
 
