#!/bin/sh



jj="27-09"
## jj=`date '+%d-%m'`
# first for North
echo "###start North####"

DAY=` date +%d`
YEAR=` date +%Y`
MONTH=`date +%m`
Time=`date +%H%M%S`

cd /home/NCOR6649/scripts/alcatel/










zcat /home/NCOR6649/logs/dt_site/alu_dt_$DAY$MONTH*.Z | nawk ' FS="|" ,OFS="|" { print "Alcatel",$0 } ' > /home/NCOR6649/logs/dt_site/nwd_dt 

 
 
zcat /home/NCOR6649/logs/dt_site/mot_dt_$DAY$MONTH*.Z | nawk ' FS="|" ,OFS="|" { print "Motorola",$1,$2,$4,$5 } ' >> /home/NCOR6649/logs/dt_site/nwd_dt 





zcat /home/NCOR6649/logs/dt_site/hu_dt_$DAY$MONTH*.Z | nawk ' FS="," ,OFS="|" { print "Huawei",$1,$2,"",$5 } ' >> /home/NCOR6649/logs/dt_site/nwd_dt


zcat /home/NCOR6649/logs/zte/zte_down_st_$YEAR$MONTH$DAY.Z | nawk ' FS="|" ,OFS="|" { print "ZTE",$1,$2," ",$3} ' >> /home/NCOR6649/logs/dt_site/nwd_dt 

rm -f /home/NCOR6649/logs/dt_site/nwd_dt.Z
compress /home/NCOR6649/logs/dt_site/nwd_dt





echo "### End #####"



 
 
