#!/bin/sh



jj="27-09"
## jj=`date '+%d-%m'`
# first for North
echo "###start North####"

DAY=`TZ=GMT+24 date +%d`
YEAR=`TZ=GMT+24 date +%Y`
MONTH=`TZ=GMT+24 date +%m`

cd /home/NCOR6649/scripts/alcatel/

sh  ftp_cal




# compress /home/NCOR6649/logs/rsl/all_mot_rsl_site_$DAY-$MONTH 


cat /tmp/cal/omc*_cal.csv |  grep "notCleared" | nawk -f get_alm_cal |  sort -u   > /home/NOCCORDT/alu_alm.txt

rm -f  /home/NOCCORDT/alu_alm.txt.Z

compress /home/NOCCORDT/alu_alm.txt

echo "### End #####"



 
 
