#!/bin/sh



jj="27-09"
## jj=`date '+%d-%m'`
# first for North
echo "###start North####"

DAY=`TZ=GMT+24 date +%d`
YEAR=`TZ=GMT+24 date +%Y`
MONTH=`TZ=GMT+24 date +%m`


DAY1=`TZ=GMT+48 date +%d`
YEAR1=`TZ=GMT+48 date +%Y`
MONTH1=`TZ=GMT+48 date +%m`

DAY2=`TZ=GMT+72 date +%d`
YEAR2=`TZ=GMT+72 date +%Y`
MONTH2=`TZ=GMT+72 date +%m`



cd /home/NCOR6649/scripts/gprs 


zcat /tmp/ev_logs/*-$DAY2-$MONTH2.txt.Z  /tmp/ev_logs/*-$DAY1-$MONTH1.txt.Z /tmp/ev_logs/*-$DAY-$MONTH.txt.Z  | perl search.pl -l "GPRS Unavailable - No PDCHs|EGPRS Unavailable - No EGPRS" | perl search.pl -l "equipmentFailureEvent" | nawk -f first > n_rsl.txt

zcat /tmp/ev_logs/*-$DAY2-$MONTH2.txt.Z  /tmp/ev_logs/*-$DAY1-$MONTH1.txt.Z /tmp/ev_logs/*-$DAY-$MONTH.txt.Z  | perl search.pl -l "GPRS Unavailable - No GPRS" | perl search.pl -l "qualityOfServiceFailureEvent" | nawk -f first_no >> n_rsl.txt



nawk -f getmain1 n_rsl.txt|sort -u  > indexs

  nawk -f get_rsl_n n_rsl.txt |  nawk -f sep_bsc_site_date | sort -u > /home/NCOR6649/logs/gprs/gprs_mot_$DAY-$MONTH 

rm -f /home/NCOR6649/logs/gprs/gprs_mot_$DAY-$MONTH.Z
rm -f /home/NCOR6649/logs/gprs/gprs_hu_$DAY-$MONTH.Z

compress /home/NCOR6649/logs/gprs/gprs_mot_$DAY-$MONTH 

rm -f n_rsl.txt

/bin/sh /home/NCOR6649/scripts/alcatel/main_gprs


zcat /home/NCOR6649/logs/gprs/h_omc*_gprs_logs_$DAY$MONTH$YEAR.txt.Z | sort -u > /home/NCOR6649/logs/gprs/gprs_hu_$DAY-$MONTH

compress /home/NCOR6649/logs/gprs/gprs_hu_$DAY-$MONTH


gprs_mot=gprs_mot_$DAY-$MONTH
gprs_alu=gprs_alu_$DAY-$MONTH
gprs_hu=gprs_hu_$DAY-$MONTH




echo "### End #####"



 
 
