#!/bin/sh



jj="27-09"
## jj=`date '+%d-%m'`
# first for North
echo "###start North####"

DAY=`TZ=GMT+24 date +%d`
YEAR=`TZ=GMT+24 date +%Y`
MONTH=`TZ=GMT+24 date +%m`

DAY1=`TZ=GMT+48 date +%d`
YEAR1=`TZ=GMT+48 date +%Y`
MONTH1=`TZ=GMT+48 date +%m`

DAY2=`TZ=GMT+72 date +%d`
YEAR2=`TZ=GMT+72 date +%Y`
MONTH2=`TZ=GMT+72 date +%m`



cd /home/NCOR6649/scripts/gprs 


zcat `find /tmp/ev_logs -type f -mtime -9`   | perl search.pl -l "GPRS Unavailable - No PDCHs|EGPRS Unavailable - No EGPRS" | perl search.pl -l "equipmentFailureEvent" | nawk -f first > n_rsl.txt

zcat `find /tmp/ev_logs -type f -mtime -9`    | perl search.pl -l "GPRS Unavailable - No GPRS" | perl search.pl -l "qualityOfServiceFailureEvent" | nawk -f first_no >> n_rsl.txt



nawk -f getmain1 n_rsl.txt|sort -u  > indexs

  nawk -f get_rsl_n n_rsl.txt |  nawk -f sep_bsc_site_date | sort -u | nawk 'FS="|" , OFS="|" { print "Motorola",$0} ' > /home/NCOR6649/logs/gprs/weekly_gprs$DAY$MONTH 



/bin/sh /home/NCOR6649/scripts/alcatel/main_gprs_week

zcat /home/NCOR6649/logs/gprs/gprs_alu_$DAY-$MONTH.Z | sort -u | nawk 'FS="|" , OFS="|" { print "Alcatel",$0} '  >> /home/NCOR6649/logs/gprs/weekly_gprs$DAY$MONTH
  
zcat /home/NCOR6649/logs/gprs/h_omc*_gprs_logs_$DAY$MONTH$YEAR.txt.Z | sort -u | nawk 'FS="|" , OFS="|" { print "Huawei",$0} ' >> /home/NCOR6649/logs/gprs/weekly_gprs$DAY$MONTH

zcat /home/NCOR6649/logs/err/erc_gprs_week_$DAY$MONTH$YEAR.Z | sort -u | nawk 'FS="|" , OFS="|" { print "Ericsson",$0 } ' >> /home/NCOR6649/logs/gprs/weekly_gprs$DAY$MONTH
 
rm -f /home/NCOR6649/logs/gprs/weekly_gprs$DAY$MONTH.Z

compress /home/NCOR6649/logs/gprs/weekly_gprs$DAY$MONTH
 


gprs_mot=weekly_gprs$DAY$MONTH

echo -e " Nation Wide Weekly Weekly gprs report. It contains alarms from \nMotorola\nAlcatel\nHuawei\nEricsson " > gprs_ste 

(cat gprs_ste ; /usr/bin/uuencode /home/NCOR6649/logs/gprs/weekly_gprs$DAY$MONTH.Z  $gprs_mot.Z ) | mailx -s $gprs_mot nauman.khan@mobilink.net,muhammad.salman@mobilink.net,usman.ar@mobilink.net,NOOR.HUDA@mobilink.net,aasif.akram@mobilink.net 
 

cp /home/NCOR6649/logs/gprs/weekly_gprs$DAY$MONTH.Z /home/NCOR6649/logs/gprs/weekly_gprs.Z


echo "### End #####"



 
 
