#!/bin/sh

#user=`echo '"noc_core"'`
#echo  "$user"
#password=` echo '"Mobilink123"' `
#echo "$password"

#echo "$Ser"

#for file in `cat ll`;do echo " ";done

#grep "BSGSM" /usr/gsm/config/global/NE.MAP|awk '{print $2}'>./bss_name

# echo " " > ./gath 

echo " " > final
echo " " > raw
echo "" > h7_gath


dos2unix -ascii -850 fip.csv  > mfip.csv;


for i in `cat mfip.csv | perl -e 's/ //g' -w -p -i `
do

echo $i

#printf $i
msc=`printf $i | awk ' { FS="," ;print $2 } '`
m_user=`echo $i | awk ' { FS="," ;print $3 } '`
m_passwd=`echo $i | awk ' { FS="," ;print $4 } '`
m_ser=`echo  "\"$msc---O&M System\""`

media=`echo $i | awk ' { FS="," ;print $6 } '`
md_user=`echo $i | awk ' { FS="," ;print $7 } '`
md_passwd=`echo $i | awk ' { FS="," ;print $8 } '`
pt_code=`echo $i | awk ' { FS="," ;print $9 } '`
echo $m_user



 user=`echo  "\"$m_user\"" `
 password=`echo "\"$m_passwd\"" `

 echo  $msc
 echo $user


# (echo  "LGI:op=$user,PWd=$password,SER=$m_ser;";sleep 3 ; echo "LST OFCTKC: CDT=OFCCIC, QR=LOCAL;";sleep 300 ) |
# telnet  $msc 6000    | nawk -f comp  | grep $pt_code > gath




(echo  "LGI:op=$user,PWd=$password,SER=$m_ser;";sleep 3 ; echo "LST N7LNK:;"; echo "LST MDU:;"; echo "LST OFCLNK:;"; echo "LST OFC:;";sleep 7  ) | telnet  $msc 6000  >> h7_gath

# echo "ZZZZ;" 

done





