#!/bin/sh

user=`echo '"noc_core"'`
#echo  "$user"
password=` echo '"Mobilink123"' `
#echo "$password"

server="10.31.24.21"

Ser=`echo  "\"$server---O&M System\""`
last=`echo "\"---O&MSystem\""`
#echo "$Ser"

#for file in `cat ll`;do echo " ";done

#grep "BSGSM" /usr/gsm/config/global/NE.MAP|awk '{print $2}'>./bss_name

# echo " " > ./gath 

echo " " > final
echo " " > raw
echo "" > ms_gath

for i in `cat fip.csv | awk ' { FS="," ; OFS="|" ;  print $2,$4 } ' | sort -u  ` 
do



 server=`echo $i | awk ' { FS="|" ;print $1 } '`


 mgt=`echo $i | awk ' { FS="|" ;print $2 } '` 

 echo $server
echo $mgt


Ser=`echo  "\"$server---O&M System\""`
 
#tid[$j]=` echo $i | nawk ' { FS="|" ;print $6 } ' `

echo $Ser






(echo  "LGI:op=$user,PWd=$password,SER=$Ser;";sleep 3 ; echo "LST N7LNK:;"; echo "LST MDU:;"; echo "LST OFCLNK:;"; echo "LST OFC:;";sleep 15  ) | telnet  $server 6000  >> ms_gath

# echo "ZZZZ;" 

   done






