#!/usr/bin/sh
#
cd /home/NCOR6649/scripts/alcatel/cell

# touch /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell

echo "Huawei Files Status:"
echo "Huawei-OMC-1"
ftp -n -p 10.231.170.10 <<EOF
user ftpuser ftpuser

cd /export/home/noccord/logs/
hash
bin
mget hu_cell.txt

bye
EOF

#cat hu_cell.txt  |   nawk ' FS="|" ,OFS="|" { split($7,lac,"(");split(lac[2],lac_f,")");split($8,cellid,"(");split(cellid[2],cellid_f,")");print "Huawei","homc1",$1,$32,$3,$31,lac_f[1],cellid_f[1] } ' >> /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell
cat hu_cell.txt | nawk ' FS="|" ,OFS="|" { split($7,lac,"(");split(lac[2],lac_f,")");split($8,cellid,"(");split(cellid[2],cellid_f,")");print "Huawei","homc1",$1,$14,$3,$2,lac_f[1],cellid_f[1] } ' >> /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell

rm -f hu_cell.txt 
echo "-----------------------------------------------------------"
echo ""
echo "Huawei-OMC-2"
ftp -n -p 10.231.170.30 <<EOF
user ftpuser ftpuser
cd /export/home/noccord/logs/
hash
bin
mget hu_cell.txt

bye
EOF

#mv hu_cell.txt hu_hom2_cell.txt
#cat hu_cell.txt  |   nawk ' FS="|" ,OFS="|" { split($7,lac,"(");split(lac[2],lac_f,")");split($8,cellid,"(");split(cellid[2],cellid_f,")");print "Huawei","homc2",$1,$32,$3,$31,lac_f[1],cellid_f[1] } ' >> /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell
#cat hu_cell.txt | nawk ' FS="|" ,OFS="|" { split($7,lac,"(");split(lac[2],lac_f,")");split($8,cellid,"(");split(cellid[2],cellid_f,")");print "Huawei","homc2",$1,substr($3,1,3)""substr($3,5,length($3)),$3,$2,lac_f[1],cellid_f[1] } '  >> /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell
cat hu_cell.txt | nawk ' FS="|" ,OFS="|" { split($7,lac,"(");split(lac[2],lac_f,")");split($8,cellid,"(");split(cellid[2],cellid_f,")");print "Huawei","homc2",$1,$14,$3,$2,lac_f[1],cellid_f[1] } ' >> /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell
echo "-----------------------------------------------------------"
echo ""
echo "Huawei-OMC-3"
ftp -n -p 10.231.170.70 <<EOF
user ftpuser ftpuser

cd /export/home/noccord/logs/
hash
bin
mget hu_cell.txt



bye
EOF

#cat hu_cell.txt  |  nawk ' FS="|" ,OFS="|" { split($7,lac,"(");split(lac[2],lac_f,")");split($8,cellid,"(");split(cellid[2],cellid_f,")");print "Huawei","homc3",$1,$32,$3,$31,lac_f[1],cellid_f[1] } ' >> /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell
#cat hu_cell.txt | nawk ' FS="|" ,OFS="|" { split($7,lac,"(");split(lac[2],lac_f,")");split($8,cellid,"(");split(cellid[2],cellid_f,")");print "Huawei","homc3",$1,substr($3,1,3)""substr($3,5,length($3)),$3,$2,lac_f[1],cellid_f[1] } '  >> /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell
cat hu_cell.txt | nawk ' FS="|" ,OFS="|" { split($7,lac,"(");split(lac[2],lac_f,")");split($8,cellid,"(");split(cellid[2],cellid_f,")");print "Huawei","homc3",$1,$14,$3,$2,lac_f[1],cellid_f[1] } ' >> /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell


echo "-----------------------------------------------------------"
echo ""
echo "Huawei-OMC-4"
ftp -n -p 10.231.170.104 <<EOF
user ftpatae Ftpat@e1 
dir /export/home/ftpatae/noccord/logs/hu_cell.txt
cd  /export/home/ftpatae/noccord/logs/ 
hash
bin
mget hu_cell.txt

bye
EOF

 #cat hu_cell.txt  |   nawk ' FS="|" ,OFS="|" { split($7,lac,"(");split(lac[2],lac_f,")");split($8,cellid,"(");split(cellid[2],cellid_f,")");print "Huawei","homc4",$1,$32,$3,$31,lac_f[1],cellid_f[1] } ' >> /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell
#cat hu_cell.txt | nawk ' FS="|" ,OFS="|" { split($7,lac,"(");split(lac[2],lac_f,")");split($8,cellid,"(");split(cellid[2],cellid_f,")");print "Huawei","homc4",$1,substr($3,1,3)""substr($3,5,length($3)),$3,$2,lac_f[1],cellid_f[1] } '  >> /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell
cat hu_cell.txt | nawk ' FS="|" ,OFS="|" { split($7,lac,"(");split(lac[2],lac_f,")");split($8,cellid,"(");split(cellid[2],cellid_f,")");print "Huawei","homc4",$1,$14,$3,$2,lac_f[1],cellid_f[1] } ' >> /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell
echo "-----------------------------------------------------------"
echo ""
echo "Huawei-OMC-5"
ftp -n -p 10.231.250.227 <<EOF
user FTPU2000 Ftp@U2000 
dir /home/FTPU2000/noccord/logs/hu_cell.txt
cd  /home/FTPU2000/noccord/logs/
hash
bin
mget hu_cell.txt

bye
EOF

 #cat hu_cell.txt  |   nawk ' FS="|" ,OFS="|" { split($7,lac,"(");split(lac[2],lac_f,")");split($8,cellid,"(");split(cellid[2],cellid_f,")");print "Huawei","homc4",$1,$32,$3,$31,lac_f[1],cellid_f[1] } ' >> /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell
#cat hu_cell.txt | nawk ' FS="|" ,OFS="|" { split($7,lac,"(");split(lac[2],lac_f,")");split($8,cellid,"(");split(cellid[2],cellid_f,")");print "Huawei","homc5",$1,substr($3,1,3)""substr($3,5,length($3)),$3,$2,lac_f[1],cellid_f[1] } '  >> /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell
cat hu_cell.txt | nawk ' FS="|" ,OFS="|" { split($7,lac,"(");split(lac[2],lac_f,")");split($8,cellid,"(");split(cellid[2],cellid_f,")");print "Huawei","homc5",$1,$14,$3,$2,lac_f[1],cellid_f[1] } ' >> /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell


echo "-----------------------------------------------------------"
echo ""
echo "Huawei-OMC-6"
ftp -n -p 10.231.250.211 <<EOF
user FTPU2000 Ftp@U2000 
dir /home/FTPU2000/noccord/logs/hu_cell.txt
cd  /home/FTPU2000/noccord/logs/
hash
bin
mget hu_cell.txt

bye
EOF

 #cat hu_cell.txt  |   nawk ' FS="|" ,OFS="|" { split($7,lac,"(");split(lac[2],lac_f,")");split($8,cellid,"(");split(cellid[2],cellid_f,")");print "Huawei","homc4",$1,$32,$3,$31,lac_f[1],cellid_f[1] } ' >> /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell
#cat hu_cell.txt | nawk ' FS="|" ,OFS="|" { split($7,lac,"(");split(lac[2],lac_f,")");split($8,cellid,"(");split(cellid[2],cellid_f,")");print "Huawei","homc5",$1,substr($3,1,3)""substr($3,5,length($3)),$3,$2,lac_f[1],cellid_f[1] } '  >> /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell
cat hu_cell.txt | nawk ' FS="|" ,OFS="|" { split($7,lac,"(");split(lac[2],lac_f,")");split($8,cellid,"(");split(cellid[2],cellid_f,")");print "Huawei","homc6",$1,$14,$3,$2,lac_f[1],cellid_f[1] } ' >> /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell



<<COMMENT1

echo "-----------------------------------------------------------"
echo ""
echo "Motorola Files Status:"

echo "mk5sys1"

perl sunfire2.pl
sleep 6 
ftp -n -p 10.231.10.65 <<EOF
user ftpuser ftpuser
cd /home/omcadmin/
hash
bin
mget cellexport.out

bye
EOF

cat cellexport.out | nawk ' FS="\t" ,OFS="|" { split($4,cell,"-");print "Motorola","mk5sys1",$1,$2,$2,$3,cell[3],cell[4] } ' | sed 's/ //g' >> /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell
echo "-----------------------------------------------------------"
echo ""
echo "sunfire3"
perl sunfire3.pl
sleep 6
ftp -n -p 10.231.10.30 <<EOF
user ftpuser ftpuser
cd /home/omcadmin/
hash
bin
mget cellexport.out

bye
EOF

cat cellexport.out | nawk ' FS="\t" ,OFS="|" { split($4,cell,"-");print "Motorola","Sunfire3",$1,$2,$2,$3,cell[3],cell[4] } ' | sed 's/ //g' >> /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell


echo "-----------------------------------------------------------"
echo ""

perl sunfire4.pl
sleep 6
echo "sunfire4"
ftp -n -p 10.231.10.50 <<EOF
user ftpuser ftpuser
cd /home/omcadmin/
hash
bin
mget cellexport.out

bye
EOF

cat cellexport.out | nawk ' FS="\t" ,OFS="|" { split($4,cell,"-");print "Motorola","Sunfire4",$1,$2,$2,$3,cell[3],cell[4] } ' | sed 's/ //g' >> /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell



echo "-----------------------------------------------------------"
echo "End of Script"
echo "-----------------------------------------------------------"
<<COMMENT1

