#!/usr/bin/sh

DAY=` date +%d`
YEAR=` date +%Y`
MONTH=`date +%m`

cd /home/NCOR6649/scripts/alcatel/cell
touch cell_ste
nwd_cell=nwd_bsc_bts_cell_$DAY-$MONTH.csv

echo "Daily NWD BSS BSC , Site, Cell,Site_id,LAC,Cell Id  Information" > cell_ste
echo "" >> cell_ste
echo "*********Summary**********" >> cell_ste
echo "Vendor|OMC|BSC|Sites|Cells" >> cell_ste
echo "==========================" >> cell_ste
for i in ` zcat /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell.csv.Z |  nawk ' FS="," ,OFS="," { print $1,$2 }' | sort -u `
do

bsc=`zcat /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell.csv.Z | grep $i | nawk ' FS="," ,OFS="," { print $3}' | sort -u | wc -l `
site=`zcat /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell.csv.Z | grep $i | nawk ' FS="," ,OFS="," { print $4}' | sort -u | wc -l `
cells=`zcat /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell.csv.Z | grep $i | nawk ' FS="," ,OFS="," { print $5}'   | wc -l `
 
echo "$i   |$bsc|$site|$cells" | sed 's/ //g' >> cell_ste




done
echo "============================" >> cell_ste
echo "Cell Data files are generated at 5:00 am daily" >> cell_ste


(cat cell_ste ; /usr/bin/uuencode /home/NCOR6649/logs/cell/taskdata/nwd_bsc_bts_cell.csv.Z  $nwd_cell.Z ) | mailx -s $nwd_cell nauman.khan@mobilink.net,usman.ar@mobilink.net,NOOR.HUDA@mobilink.net,marvi.waheed@mobilink.net,hashim.mushtaq@mobilink.net,farrukh.hussain@mobilink.net,aamir.mahmood@mobilink.net 
