#!/bin/sh



jj="27-09"
## jj=`date '+%d-%m'`
# first for North
echo "###start North####"

DAY=` date +%d`
YEAR=` date +%Y`
MONTH=` date +%m`

#cd /home/oann/scripts/RSL

#` cp /home/Motorola/ev_logs/s*.txt.Z /tmp/ev_logs/
 
echo "omc1"

ftp -n -p 10.231.160.1 <<EOF
user omc3ftp omc3ftp
hash
bin
cd ACME

mget BSSConf.alcomc1."$YEAR$MONTH$DAY"05*

bye

EOF


echo "omc2"
ftp -n -p 10.231.80.1 <<EOF
user omc3ftp omc3ftp
hash
bin
cd ACME

mget BSSConf.alcomc2."$YEAR$MONTH$DAY"05*
bye

EOF


echo "omc3"
ftp -n -p 10.231.90.4 <<EOF
user omc3ftp omc3ftp
hash
bin
cd ACME

 mget BSSConf.alcomc3m."$YEAR$MONTH$DAY"05* 
bye

EOF


echo "omc4"
ftp -n -p 10.231.140.1 <<EOF
user omc3ftp omc3ftp
hash
bin
cd ACME
 mget BSSConf.alcomc4m."$YEAR$MONTH$DAY"05* 

bye

EOF


echo "omc5"
ftp -n -p 10.231.150.1 <<EOF
user omc3ftp omc3ftp
hash
bin
cd ACME
mget BSSConf.alcomc5m."$YEAR$MONTH$DAY"05* 
bye

EOF

compress BSSConf*

# gzcat HAL*.tgz | grep "LOSS-OF-ALL-CHAN" | nawk -f get_alm_hal | grep "\/18"


echo "### End #####"


 zcat BSSConf* | nawk -f bsc | sort -u  > bsc.txt

 zcat BSSConf* | nawk -f cell | sort -u  > cell.txt

rm -f BSSConf*


ssh NOCCORDT@sunfire4 'cd /home/omcadmin/ ; ./cellexport.csh ;  cat /home/omcadmin/cellexport.out  ' | awk ' { print $0,"Sunfire4" } ' > mot_cell.txt
ssh NOCCORDT@sunfire3 'cd /home/omcadmin/ ; ./cellexport.csh ;  cat /home/omcadmin/cellexport.out  '  | awk ' { print $0,"Sunfire3" } ' >> mot_cell.txt
ssh NOCCORDT@10.231.10.65 'cd /home/omcadmin/ ; ./cellexport.csh ;  cat /home/omcadmin/cellexport.out ' | awk ' { print $0,"mk5sys" } ' >> mot_cell.txt 
 
