#!/bin/sh



jj="27-09"
## jj=`date '+%d-%m'`
# first for North
echo "###start North####"

DAY=` date +%d`
YEAR=` date +%Y`
MONTH=` date +%m`

#cd /home/oann/scripts/RSL
cd /home/NCOR6649/scripts/alcatel/cell

#` cp /home/Motorola/ev_logs/s*.txt.Z /tmp/ev_logs/
 
echo "omc1"

ftp -n -p 10.231.160.1 <<EOF
user omc3ftp omc3ftp
hash
bin
cd ACME

mget BSSConf.alcomc1."$YEAR$MONTH$DAY"05*

bye

EOF



compress BSSConf*



 zcat BSSConf* | nawk -f bsc | sort -u  > bsc.txt

 zcat BSSConf* | nawk -f cell | sort -u  > cell.txt

# cat bsc.txt | grep -v "^$" | grep -v "#" | sort -t "," +1 -2n +3 > bsc_sort

cat bsc.txt | grep -v "^$" | grep -v "#" | nawk ' FS="," ,OFS="," { print $2,$1,$3 } ' | sed 's/ //g' | sort -t "," -k 1n,1n > bsc_sort
cat cell.txt |  nawk ' FS="," ,OFS="," { print $1,$7,$2,$3,$4,$5 } ' | sort -u | grep -v "^$" | grep -v ",,,,," | grep -v "#" |  sed 's/ //g' | sort -t "," -k 1n,1n  > cell_sort

# join -t "," -1 1 -2 1    -o 1.1,1.2,1.3,2.6,2.3,2.4,2.5 bsc_sort cell_sort  |   nawk ' FS="," ,OFS="|" { print "Alcatel",$1,$3,substr($4,1,7)""substr($4,9,length($4)),$4,$5,$6,$7 } ' |  grep -v "BSC_NAME" > nwd_bsc_bts_cell

touch nwd_bsc_bts_cell

for i in `cat bsc_sort`
do
a=`echo $i | nawk ' FS="," ,OFS="," { print $1 } ' `
b=`echo $i | nawk ' FS="," ,OFS="," { print $2 } ' `
c=`echo $i | nawk ' FS="," ,OFS="," { print $3 } ' `

for j in `cat cell_sort | grep "$a,"`
do
aa=`echo $j | nawk ' FS="," ,OFS="," { print $1 } ' `

if [ $aa -eq  $a ]; then 
 echo $j | nawk -v omc=$b -v bsc=$c ' FS="," ,OFS="|" { print "Alcatel",omc,bsc,substr($6,1,7)""substr($6,9,length($6)),$6,$3,$4,$5 } ' >> nwd_bsc_bts_cell  
fi

done

 done

rm -f BSSConf*
