#!/bin/sh



jj="27-09"
## jj=`date '+%d-%m'`
# first for North
echo "###start North####"

DAY=`TZ=GMT+24 date +%d`
YEAR=`TZ=GMT+24 date +%Y`
MONTH=`TZ=GMT+24 date +%m`


mot_rsl=mot_rsl_$DAY$MONTH$YEAR
hu_rsl=hu_rsl_$DAY$MONTH$YEAR

zcat /home/NCOR6649/logs/huawei/lapd_genset_low*_vol_$DAY$MONTH$YEAR.txt.Z | sort -u > /home/NCOR6649/logs/huawei/hu_lapd_genset_low.txt

rm -f hu_lapd_genset_low.txt.Z

rm -f /home/NCOR6649/logs/huawei/hu_lapd_genset_low.txt.Z
  
compress /home/NCOR6649/logs/huawei/hu_lapd_genset_low.txt 

/usr/bin/uuencode /home/NCOR6649/logs/huawei/hu_lapd_genset_low.txt.Z $hu_rsl.txt.Z | mailx -s $hu_rsl nauman.khan@mobilink.net,muhammad.salman@mobilink.net,usman.ar@mobilink.net,NOOR.HUDA@mobilink.net

# rm -f hu_lapd_genset_low.txt.Z


echo "### End #####"



 
 
