#!/bin/sh



jj="27-09"
## jj=`date '+%d-%m'`
# first for North
echo "###start North####"

DAY=`TZ=GMT+24 date +%d`
YEAR=`TZ=GMT+24 date +%Y`
MONTH=`TZ=GMT+24 date +%m`


mot_rsl=mot_rsl_$DAY$MONTH$YEAR
hu_rsl=hu_rsl_$DAY$MONTH$YEAR


/usr/bin/uuencode /home/NCOR6649/logs/rsl/all_mot_rsl_site_$DAY-$MONTH.Z $mot_rsl.txt.Z | mailx -s $mot_rsl nauman.khan@mobilink.net,muhammad.salman@mobilink.net,usman.ar@mobilink.net,NOOR.HUDA@mobilink.net




echo "### End #####"



 
 
