#!/bin/sh



jj="27-09"
## jj=`date '+%d-%m'`
# first for North
echo "###start North####"

DAY=`TZ=GMT+48 date +%d`
YEAR=`TZ=GMT+48 date +%Y`
MONTH=`TZ=GMT+48 date +%m`


DAY1=`TZ=GMT+72 date +%d`
YEAR1=`TZ=GMT+72 date +%Y`
MONTH1=`TZ=GMT+72 date +%m`

DAY2=`TZ=GMT+96 date +%d`
YEAR2=`TZ=GMT+96 date +%Y`
MONTH2=`TZ=GMT+96 date +%m`



cd /home/NCOR6649/scripts/RSL

# perl sunfire2.pl

mkdir /tmp/ev_logs/
chmod 777 /tmp/ev_logs/


#cp /home/Motorola/ev_logs/*.txt.Z /tmp/ev_logs/
 
# zcat /tmp/ev_logs/*-$DAY2-$MONTH2.txt.Z  /tmp/ev_logs/*-$DAY1-$MONTH1.txt.Z /tmp/ev_logs/*-$DAY-$MONTH.txt.Z    | perl search.pl -l "Last RSL Link Failure" | perl search.pl -l -v "HANDLING" |nawk -f first > n_rsl.txt

zcat /tmp/ev_logs/*-$DAY2-$MONTH2.txt.Z  /tmp/ev_logs/*-$DAY1-$MONTH1.txt.Z /tmp/ev_logs/*-$DAY-$MONTH.txt.Z | perl /home/NCOR6649/scripts/RSL/search.pl -l "stateChangeEvent  -  SITE" | nawk -f getmain2| nawk -f first_new_dt > n_rsl.txt

nawk -f getmain1 n_rsl.txt|sort -u  > indexs

  nawk -f get_rsl_n n_rsl.txt | sort -u | nawk -f sep_bsc_site_date > /home/NCOR6649/logs/rsl/all_mot_rsl_site_$DAY-$MONTH 

rm -f /home/NCOR6649/logs/rsl/all_mot_rsl_site_$DAY-$MONTH.Z

rm -f /home/NCOR6649/logs/rsl/Motorola.txt.Z


compress /home/NCOR6649/logs/rsl/all_mot_rsl_site_$DAY-$MONTH
cp /home/NCOR6649/logs/rsl/all_mot_rsl_site_$DAY-$MONTH.Z /home/NCOR6649/logs/rsl/Motorola.txt.Z 

rm -f n_rsl.txt


# sh mail_rsl_mot


#  sh mail_rsl_hu



echo "### End #####"



 
 
