#!/bin/sh



jj="27-09"
## jj=`date '+%d-%m'`
# first for North
echo "###start North####"

DAY=`TZ=GMT+48 date +%d`
YEAR=`TZ=GMT+48 date +%Y`
MONTH=`TZ=GMT+48 date +%m`

cd /home/oann/scripts/RSL

# cp /home/Motorola/ev_logs/s*.txt.Z /tmp/ev_logs/
 
zcat /tmp/ev_logs/s*-$DAY-$MONTH.txt.Z  | perl search.pl -l "Last RSL Link Failure" | nawk -f first > n_rsl.txt

nawk -f getmain1 n_rsl.txt|sort -u  > indexs

  nawk -f get_rsl_n n_rsl.txt | sort -u | nawk -f sep_bsc_site_date > /home/oann/logs/rsl/all_mot_rsl_site_$DAY-$MONTH 

rm -f /home/oann/logs/rsl/all_mot_rsl_site_$DAY-$MONTH.Z

compress /home/oann/logs/rsl/all_mot_rsl_site_$DAY-$MONTH 

rm -f n_rsl.txt


#sh mail_rsl_mot
#sh mail_rsl_hu



echo "### End #####"



 
 
