#!/bin/sh



jj="27-09"
## jj=`date '+%d-%m'`
# first for North
echo "###start North####"

DAY=`TZ=GMT+24 date +%d`
YEAR=`TZ=GMT+24 date +%Y`
MONTH=`TZ=GMT+24 date +%m`


DAY1=`TZ=GMT+48 date +%d`
YEAR1=`TZ=GMT+48 date +%Y`
MONTH1=`TZ=GMT+48 date +%m`

DAY2=`TZ=GMT+72 date +%d`
YEAR2=`TZ=GMT+72 date +%Y`
MONTH2=`TZ=GMT+72 date +%m`


cd /home/oann/scripts/RSL

# -07-06.txt.Z 
zcat /tmp/ev_logs/*-$DAY2-$MONTH2.txt.Z  /tmp/ev_logs/*-$DAY1-$MONTH1.txt.Z /tmp/ev_logs/*-$DAY-$MONTH.txt.Z  | perl search.pl -l "Last RSL Link Failure" | perl search.pl -l -v "HANDLING" | nawk -f first > n_rsl.txt

nawk -f getmain1 n_rsl.txt|sort -u  > indexs

  nawk -f get_rsl_n n_rsl.txt | sort -u | nawk -f sep_bsc_site_date > /home/oann/logs/rsl/mot_week_rsl_$DAY-$MONTH 

rm -f /home/oann/logs/rsl/mot_week_rsl_$DAY-$MONTH.Z

compress /home/oann/logs/rsl/mot_week_rsl_$DAY-$MONTH 

rm -f n_rsl.txt




echo "### End #####"



 
 
